[package]
name = "rust-command-line-prompt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"

[dev-dependencies]
mockall = "0.12.1"

