name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
        - name: Get Repo
          run: ls
        - name: Change directory to project
          run: cd rust-command-line-prompt
        - name: Run tests
          run: cargo test --verbose
